project_id = "ygsznjehglazxhjvqoxt"

[functions.parse-task]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false
